# Generated by Django 3.2 on 2021-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
            ],
        ),
    ]
