# Generated by Django 3.2 on 2021-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_score_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
