# Generated by Django 3.2 on 2021-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210507_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='begin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beg', models.DateTimeField(null=True)),
                ('quizid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
