# Generated by Django 3.2 on 2021-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=255, null=True),
        ),
    ]
