# Generated by Django 3.2 on 2021-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questions_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
