# Generated by Django 3.2 on 2021-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20210510_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='pvtquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvtquizID', models.CharField(max_length=255, null=True)),
                ('promt', models.CharField(max_length=300, null=True)),
                ('option1', models.CharField(max_length=300, null=True)),
                ('option2', models.CharField(max_length=300, null=True)),
                ('option3', models.CharField(max_length=300, null=True)),
                ('option4', models.CharField(max_length=300, null=True)),
                ('correct', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pvtquiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('number_of_questions', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
