# Generated by Django 3.2 on 2021-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_pvtquestion_pvtquiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pvtquiz',
            new_name='pvtquizinfo',
        ),
    ]
