# Generated by Django 3.2 on 2021-05-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_rename_pvtquiz_pvtquizinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='pvtquizresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvtuserID', models.CharField(max_length=255, null=True)),
                ('pvtquizID', models.CharField(max_length=255, null=True)),
                ('pvtquestionID', models.CharField(max_length=255, null=True)),
                ('response', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
