# Generated by Django 3.2 on 2021-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_pvtquizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtquizresponse',
            name='correct',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
