# Generated by Django 3.2 on 2021-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20210515_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='pvtscores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('response1', models.CharField(max_length=200, null=True)),
                ('response2', models.CharField(max_length=200, null=True)),
                ('response3', models.CharField(max_length=200, null=True)),
                ('response4', models.CharField(max_length=200, null=True)),
                ('response5', models.CharField(max_length=200, null=True)),
                ('response6', models.CharField(max_length=200, null=True)),
                ('response7', models.CharField(max_length=200, null=True)),
                ('response8', models.CharField(max_length=200, null=True)),
                ('response9', models.CharField(max_length=200, null=True)),
                ('response10', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
