# Generated by Django 3.2 on 2021-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_pvtscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='pvtbegin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beg', models.DateTimeField(null=True)),
                ('quizid', models.CharField(max_length=255, null=True)),
                ('userid', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pvtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.DateTimeField(null=True)),
                ('quizid', models.CharField(max_length=255, null=True)),
                ('userid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
