# Generated by Django 3.2 on 2021-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_pvtbegin_pvtend'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtscores',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
