# Generated by Django 3.2 on 2021-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_pvtscores_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtscores',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
