# Generated by Django 3.2 on 2021-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_pvtscores_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtquizinfo',
            name='publicPassword',
            field=models.BooleanField(default=False),
        ),
    ]
