# Generated by Django 3.2 on 2021-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.CharField(max_length=255, null=True)),
                ('promt', models.CharField(max_length=300, null=True)),
                ('option1', models.CharField(max_length=300, null=True)),
                ('option2', models.CharField(max_length=300, null=True)),
                ('option3', models.CharField(max_length=300, null=True)),
                ('option4', models.CharField(max_length=300, null=True)),
                ('correct', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('number_of_questions', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
